# Generated by Django 5.2.1 on 2025-12-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=64)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutritionAPI.day')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('polyunsaturated_fat', models.FloatField()),
                ('monounsaturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('vitamin_A', models.FloatField()),
                ('vitamin_C', models.FloatField()),
                ('calcium', models.FloatField()),
                ('meal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='nutritionAPI.meal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_day_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'date', 'meal_name')},
        ),
    ]
