# Generated by Django 5.2.1 on 2026-01-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_calories', models.IntegerField()),
                ('goal_protein', models.IntegerField()),
                ('goal_carbs', models.IntegerField()),
                ('goal_fat', models.IntegerField()),
                ('current_weight', models.FloatField()),
                ('goal_weight', models.FloatField()),
                ('goal', models.CharField(max_length=64)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
