# Generated by Django 5.2.1 on 2025-12-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0003_alter_meal_meal_name_meal_unique_meal_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meal',
            name='unique_meal_per_user',
        ),
    ]
