# Generated by Django 5.2.1 on 2025-12-22 18:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0004_remove_meal_unique_meal_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'date', 'meal_name')},
        ),
    ]
