# Generated by Django 5.2.1 on 2026-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0005_alter_meal_unique_together_meal_user_alter_day_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('serving_size', models.CharField(max_length=64)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('polyunsaturated_fat', models.FloatField()),
                ('monounsaturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('vitamin_A', models.FloatField()),
                ('vitamin_C', models.FloatField()),
                ('calcium', models.FloatField()),
            ],
        ),
    ]
