# Generated by Django 5.2.1 on 2026-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0006_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='brand',
            field=models.CharField(default='MSU', max_length=64),
        ),
    ]
