# Generated by Django 5.2.1 on 2026-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0007_foods_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='serving_size',
            field=models.CharField(default='1 serving', max_length=64),
        ),
    ]
