# Generated by Django 5.2.1 on 2026-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0008_fooddata_serving_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foods',
            constraint=models.UniqueConstraint(fields=('food_name', 'brand'), name='unique_food_per_brand'),
        ),
    ]
