# Generated by Django 5.2.1 on 2026-05-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0009_foods_unique_food_per_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
