# Generated by Django 5.2.1 on 2026-05-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0010_foods_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='date_last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
