# Generated by Django 5.2.1 on 2026-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0011_foods_date_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
