# Generated by Django 5.2.1 on 2026-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0013_remove_meal_saved_savedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmeal',
            name='foods',
            field=models.ManyToManyField(to='nutritionAPI.fooddata'),
        ),
    ]
