# Generated by Django 5.2.1 on 2026-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0014_savedmeal_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmeal',
            name='foods',
            field=models.ManyToManyField(to='nutritionAPI.foods'),
        ),
    ]
