# Generated by Django 5.2.1 on 2026-05-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0015_alter_savedmeal_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='food_from',
            field=models.ForeignKey(default=1252, on_delete=django.db.models.deletion.CASCADE, related_name='food_derived_from', to='nutritionAPI.foods'),
        ),
    ]
