# Generated by Django 5.2.1 on 2026-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionAPI', '0016_fooddata_food_from'),
        ('nutritionAPI', '0016_savedmeal_serving_multipliers'),
    ]

    operations = [
    ]
